global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'ousia-gateway'
    static_configs:
      - targets: ['gateway:9000']

  - job_name: 'ousia-sidecars'
    static_configs:
      - targets: 
        - 'service-a:15000'
        - 'service-b:15000'
